# Generated by Django 4.1.3 on 2022-12-09 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Никнейм')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия Имя')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-Mail')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('intro', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default='profile/default.jpg', null=True, upload_to='profile')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('youtube', models.UUIDField(blank=True, null=True, verbose_name='YouTube')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Мой сайт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('skills', models.ManyToManyField(blank=True, to='users.skill', verbose_name='Скилы')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['created_at'],
            },
        ),
    ]
