# Generated by Django 4.1.3 on 2022-12-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_city_alter_profile_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
    ]
